sudo: required
dist: xenial
language: python
python:
  - "3.6"


before_install:
  - sudo apt-get update -qq

install:
  - pip install -r requirements.txt
  - pip3 install --upgrade pip
# command to run tests
script:
  - pytest